# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

recombineC <- function(hap1, hap2, nchr, chrlen, chrsnp, snppos) {
    .Call('quantgen_recombineC', PACKAGE = 'quantgen', hap1, hap2, nchr, chrlen, chrsnp, snppos)
}

